// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2026-02-27T14:02:45Z

package pumpamm

import "github.com/gagliardetto/solana-go"

const ProgramID string = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
const ProgramName string = "pump_amm"
const ProgramVersion string = "0.1.0"

var ProgramKey = solana.MustPublicKeyFromBase58(ProgramID)
