// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2026-02-27T14:02:44Z

package pump

import "github.com/gagliardetto/solana-go"

const ProgramID string = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"
const ProgramName string = "pump"
const ProgramVersion string = "0.1.0"

var ProgramKey = solana.MustPublicKeyFromBase58(ProgramID)
