// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2026-02-28T16:23:10Z

package pumpfees

import (
	"bytes"
	"fmt"

	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

var BondingCurveDiscriminator = []byte{23, 183, 248, 55, 96, 216, 172, 96}

func (a *BondingCurve) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account BondingCurve: data too short")
	}
	if !bytes.Equal(data[:8], BondingCurveDiscriminator) {
		return fmt.Errorf("account BondingCurve: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *BondingCurve) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var FeeConfigDiscriminator = []byte{143, 52, 146, 187, 219, 123, 76, 155}

func (a *FeeConfig) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account FeeConfig: data too short")
	}
	if !bytes.Equal(data[:8], FeeConfigDiscriminator) {
		return fmt.Errorf("account FeeConfig: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *FeeConfig) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var GlobalDiscriminator = []byte{167, 232, 232, 177, 200, 108, 114, 127}

func (a *Global) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account Global: data too short")
	}
	if !bytes.Equal(data[:8], GlobalDiscriminator) {
		return fmt.Errorf("account Global: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *Global) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var PoolDiscriminator = []byte{241, 154, 109, 4, 17, 177, 109, 188}

func (a *Pool) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account Pool: data too short")
	}
	if !bytes.Equal(data[:8], PoolDiscriminator) {
		return fmt.Errorf("account Pool: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *Pool) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}

var SharingConfigDiscriminator = []byte{216, 74, 9, 0, 56, 140, 93, 75}

func (a *SharingConfig) Unmarshal(data []byte) error {
	if len(data) < 8 {
		return fmt.Errorf("account SharingConfig: data too short")
	}
	if !bytes.Equal(data[:8], SharingConfigDiscriminator) {
		return fmt.Errorf("account SharingConfig: discriminator mismatch")
	}
	dec := bin.NewBorshDecoder(data[8:])
	return dec.Decode(a)
}

func (a *SharingConfig) Address(pubkey solana.PublicKey) solana.PublicKey {
	return pubkey
}
