// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2026-02-28T16:23:10Z

package pumpfees

import (
	"bytes"
	"fmt"

	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

var CreateFeeSharingConfigDiscriminator = []byte{195, 78, 86, 76, 111, 52, 251, 213}

type CreateFeeSharingConfigArgs struct{}

type CreateFeeSharingConfigAccounts struct {
	EventAuthority        solana.PublicKey
	Program               solana.PublicKey
	Payer                 solana.PublicKey
	Global                solana.PublicKey
	Mint                  solana.PublicKey
	SharingConfig         solana.PublicKey
	SystemProgram         solana.PublicKey
	BondingCurve          solana.PublicKey
	PumpProgram           solana.PublicKey
	PumpEventAuthority    solana.PublicKey
	Pool                  solana.PublicKey
	PumpAmmProgram        solana.PublicKey
	PumpAmmEventAuthority solana.PublicKey
}

func (a CreateFeeSharingConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 13)
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultCreateFeeSharingConfigProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateFeeSharingConfigProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.Payer, true, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.SharingConfig, true, false))
	var defaultCreateFeeSharingConfigSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateFeeSharingConfigSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, true, false))
	var defaultCreateFeeSharingConfigPumpProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateFeeSharingConfigPumpProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.PumpEventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Pool, true, false))
	var defaultCreateFeeSharingConfigPumpAmmProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultCreateFeeSharingConfigPumpAmmProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.PumpAmmEventAuthority, false, false))
	return metas
}

func BuildCreateFeeSharingConfig(accounts CreateFeeSharingConfigAccounts, args CreateFeeSharingConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(CreateFeeSharingConfigDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveCreateFeeSharingConfigEventAuthorityPDA(accounts CreateFeeSharingConfigAccounts, args CreateFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateFeeSharingConfigGlobalPDA(accounts CreateFeeSharingConfigAccounts, args CreateFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveCreateFeeSharingConfigSharingConfigPDA(accounts CreateFeeSharingConfigAccounts, args CreateFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{115, 104, 97, 114, 105, 110, 103, 45, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveCreateFeeSharingConfigBondingCurvePDA(accounts CreateFeeSharingConfigAccounts, args CreateFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveCreateFeeSharingConfigPumpEventAuthorityPDA(accounts CreateFeeSharingConfigAccounts, args CreateFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveCreateFeeSharingConfigPumpAmmEventAuthorityPDA(accounts CreateFeeSharingConfigAccounts, args CreateFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{12, 20, 222, 252, 130, 94, 198, 118, 148, 37, 8, 24, 187, 101, 64, 101, 244, 41, 141, 49, 86, 213, 113, 180, 212, 248, 9, 12, 24, 233, 168, 99}))
}

var GetFeesDiscriminator = []byte{231, 37, 126, 85, 207, 91, 63, 52}

type GetFeesArgs struct {
	IsPumpPool        bool        `bin:"is_pump_pool"`
	MarketCapLamports bin.Uint128 `bin:"market_cap_lamports"`
	TradeSizeLamports uint64      `bin:"trade_size_lamports"`
}

type GetFeesAccounts struct {
	FeeConfig       solana.PublicKey
	ConfigProgramId solana.PublicKey
}

func (a GetFeesAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 2)
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, false, false))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	return metas
}

func BuildGetFees(accounts GetFeesAccounts, args GetFeesArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(GetFeesDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveGetFeesFeeConfigPDA(accounts GetFeesAccounts, args GetFeesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var InitializeFeeConfigDiscriminator = []byte{62, 162, 20, 133, 121, 65, 145, 27}

type InitializeFeeConfigArgs struct{}

type InitializeFeeConfigAccounts struct {
	Admin           solana.PublicKey
	FeeConfig       solana.PublicKey
	SystemProgram   solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a InitializeFeeConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	var defaultInitializeFeeConfigAdmin = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("8LWu7QM2dGR1G8nKDHthckea57bkCzXyBTAKPJUBDHo8")
	}

	metas = append(metas, solana.NewAccountMeta(defaultInitializeFeeConfigAdmin(), true, false))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	var defaultInitializeFeeConfigSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultInitializeFeeConfigSystemProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildInitializeFeeConfig(accounts InitializeFeeConfigAccounts, args InitializeFeeConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(InitializeFeeConfigDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveInitializeFeeConfigFeeConfigPDA(accounts InitializeFeeConfigAccounts, args InitializeFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveInitializeFeeConfigEventAuthorityPDA(accounts InitializeFeeConfigAccounts, args InitializeFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var ResetFeeSharingConfigDiscriminator = []byte{10, 2, 182, 95, 16, 127, 129, 186}

type ResetFeeSharingConfigArgs struct{}

type ResetFeeSharingConfigAccounts struct {
	Authority      solana.PublicKey
	Global         solana.PublicKey
	NewAdmin       solana.PublicKey
	Mint           solana.PublicKey
	SharingConfig  solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a ResetFeeSharingConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 7)
	metas = append(metas, solana.NewAccountMeta(a.Authority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.NewAdmin, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.SharingConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildResetFeeSharingConfig(accounts ResetFeeSharingConfigAccounts, args ResetFeeSharingConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(ResetFeeSharingConfigDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveResetFeeSharingConfigGlobalPDA(accounts ResetFeeSharingConfigAccounts, args ResetFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveResetFeeSharingConfigSharingConfigPDA(accounts ResetFeeSharingConfigAccounts, args ResetFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{115, 104, 97, 114, 105, 110, 103, 45, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveResetFeeSharingConfigEventAuthorityPDA(accounts ResetFeeSharingConfigAccounts, args ResetFeeSharingConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var RevokeFeeSharingAuthorityDiscriminator = []byte{18, 233, 158, 39, 185, 207, 58, 104}

type RevokeFeeSharingAuthorityArgs struct{}

type RevokeFeeSharingAuthorityAccounts struct {
	Authority      solana.PublicKey
	Global         solana.PublicKey
	Mint           solana.PublicKey
	SharingConfig  solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a RevokeFeeSharingAuthorityAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	metas = append(metas, solana.NewAccountMeta(a.Authority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.SharingConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildRevokeFeeSharingAuthority(accounts RevokeFeeSharingAuthorityAccounts, args RevokeFeeSharingAuthorityArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(RevokeFeeSharingAuthorityDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveRevokeFeeSharingAuthorityGlobalPDA(accounts RevokeFeeSharingAuthorityAccounts, args RevokeFeeSharingAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveRevokeFeeSharingAuthoritySharingConfigPDA(accounts RevokeFeeSharingAuthorityAccounts, args RevokeFeeSharingAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{115, 104, 97, 114, 105, 110, 103, 45, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveRevokeFeeSharingAuthorityEventAuthorityPDA(accounts RevokeFeeSharingAuthorityAccounts, args RevokeFeeSharingAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var TransferFeeSharingAuthorityDiscriminator = []byte{202, 10, 75, 200, 164, 34, 210, 96}

type TransferFeeSharingAuthorityArgs struct{}

type TransferFeeSharingAuthorityAccounts struct {
	Authority      solana.PublicKey
	Global         solana.PublicKey
	Mint           solana.PublicKey
	SharingConfig  solana.PublicKey
	NewAdmin       solana.PublicKey
	EventAuthority solana.PublicKey
	Program        solana.PublicKey
}

func (a TransferFeeSharingAuthorityAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 7)
	metas = append(metas, solana.NewAccountMeta(a.Authority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.SharingConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.NewAdmin, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildTransferFeeSharingAuthority(accounts TransferFeeSharingAuthorityAccounts, args TransferFeeSharingAuthorityArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(TransferFeeSharingAuthorityDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveTransferFeeSharingAuthorityGlobalPDA(accounts TransferFeeSharingAuthorityAccounts, args TransferFeeSharingAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveTransferFeeSharingAuthoritySharingConfigPDA(accounts TransferFeeSharingAuthorityAccounts, args TransferFeeSharingAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{115, 104, 97, 114, 105, 110, 103, 45, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveTransferFeeSharingAuthorityEventAuthorityPDA(accounts TransferFeeSharingAuthorityAccounts, args TransferFeeSharingAuthorityArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateAdminDiscriminator = []byte{161, 176, 40, 213, 60, 184, 179, 228}

type UpdateAdminArgs struct{}

type UpdateAdminAccounts struct {
	Admin           solana.PublicKey
	FeeConfig       solana.PublicKey
	NewAdmin        solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a UpdateAdminAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 6)
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.NewAdmin, false, false))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpdateAdmin(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateAdminDiscriminator)
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateAdminFeeConfigPDA(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpdateAdminEventAuthorityPDA(accounts UpdateAdminAccounts, args UpdateAdminArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateFeeConfigDiscriminator = []byte{104, 184, 103, 242, 88, 151, 107, 20}

type UpdateFeeConfigArgs struct {
	FeeTiers []FeeTier `bin:"fee_tiers"`
	FlatFees Fees      `bin:"flat_fees"`
}

type UpdateFeeConfigAccounts struct {
	FeeConfig       solana.PublicKey
	Admin           solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a UpdateFeeConfigAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpdateFeeConfig(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateFeeConfigDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateFeeConfigFeeConfigPDA(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpdateFeeConfigEventAuthorityPDA(accounts UpdateFeeConfigAccounts, args UpdateFeeConfigArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

var UpdateFeeSharesDiscriminator = []byte{189, 13, 136, 99, 187, 164, 237, 35}

type UpdateFeeSharesArgs struct {
	Shareholders []Shareholder `bin:"shareholders"`
}

type UpdateFeeSharesAccounts struct {
	EventAuthority            solana.PublicKey
	Program                   solana.PublicKey
	Authority                 solana.PublicKey
	Global                    solana.PublicKey
	Mint                      solana.PublicKey
	SharingConfig             solana.PublicKey
	BondingCurve              solana.PublicKey
	PumpCreatorVault          solana.PublicKey
	SystemProgram             solana.PublicKey
	PumpProgram               solana.PublicKey
	PumpEventAuthority        solana.PublicKey
	PumpAmmProgram            solana.PublicKey
	AmmEventAuthority         solana.PublicKey
	WsolMint                  solana.PublicKey
	TokenProgram              solana.PublicKey
	AssociatedTokenProgram    solana.PublicKey
	CoinCreatorVaultAuthority solana.PublicKey
	CoinCreatorVaultAta       solana.PublicKey
}

func (a UpdateFeeSharesAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 18)
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	var defaultUpdateFeeSharesProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ")
	}

	metas = append(metas, solana.NewAccountMeta(defaultUpdateFeeSharesProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.Authority, false, true))
	metas = append(metas, solana.NewAccountMeta(a.Global, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Mint, false, false))
	metas = append(metas, solana.NewAccountMeta(a.SharingConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.BondingCurve, false, false))
	metas = append(metas, solana.NewAccountMeta(a.PumpCreatorVault, true, false))
	var defaultUpdateFeeSharesSystemProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("11111111111111111111111111111111")
	}

	metas = append(metas, solana.NewAccountMeta(defaultUpdateFeeSharesSystemProgram(), false, false))
	var defaultUpdateFeeSharesPumpProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P")
	}

	metas = append(metas, solana.NewAccountMeta(defaultUpdateFeeSharesPumpProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.PumpEventAuthority, false, false))
	var defaultUpdateFeeSharesPumpAmmProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultUpdateFeeSharesPumpAmmProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.AmmEventAuthority, false, false))
	var defaultUpdateFeeSharesWsolMint = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("So11111111111111111111111111111111111111112")
	}

	metas = append(metas, solana.NewAccountMeta(defaultUpdateFeeSharesWsolMint(), false, false))
	var defaultUpdateFeeSharesTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
	}

	metas = append(metas, solana.NewAccountMeta(defaultUpdateFeeSharesTokenProgram(), false, false))
	var defaultUpdateFeeSharesAssociatedTokenProgram = func() solana.PublicKey {
		return solana.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")
	}

	metas = append(metas, solana.NewAccountMeta(defaultUpdateFeeSharesAssociatedTokenProgram(), false, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAuthority, true, false))
	metas = append(metas, solana.NewAccountMeta(a.CoinCreatorVaultAta, true, false))
	return metas
}

func BuildUpdateFeeShares(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpdateFeeSharesDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpdateFeeSharesEventAuthorityPDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpdateFeeSharesGlobalPDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{103, 108, 111, 98, 97, 108})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveUpdateFeeSharesSharingConfigPDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{115, 104, 97, 114, 105, 110, 103, 45, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpdateFeeSharesBondingCurvePDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{98, 111, 110, 100, 105, 110, 103, 45, 99, 117, 114, 118, 101})
	seeds = append(seeds, accounts.Mint[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveUpdateFeeSharesPumpCreatorVaultPDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 45, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.SharingConfig[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveUpdateFeeSharesPumpEventAuthorityPDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{1, 86, 224, 246, 147, 102, 90, 207, 68, 219, 21, 104, 191, 23, 91, 170, 81, 137, 203, 151, 245, 210, 255, 59, 101, 93, 43, 182, 253, 109, 24, 176}))
}

func DeriveUpdateFeeSharesAmmEventAuthorityPDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{12, 20, 222, 252, 130, 94, 198, 118, 148, 37, 8, 24, 187, 101, 64, 101, 244, 41, 141, 49, 86, 213, 113, 180, 212, 248, 9, 12, 24, 233, 168, 99}))
}

func DeriveUpdateFeeSharesCoinCreatorVaultAuthorityPDA(accounts UpdateFeeSharesAccounts, args UpdateFeeSharesArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{99, 114, 101, 97, 116, 111, 114, 95, 118, 97, 117, 108, 116})
	seeds = append(seeds, accounts.SharingConfig[:])
	return solana.FindProgramAddress(seeds, solana.PublicKeyFromBytes([]byte{12, 20, 222, 252, 130, 94, 198, 118, 148, 37, 8, 24, 187, 101, 64, 101, 244, 41, 141, 49, 86, 213, 113, 180, 212, 248, 9, 12, 24, 233, 168, 99}))
}

var UpsertFeeTiersDiscriminator = []byte{227, 23, 150, 12, 77, 86, 94, 4}

type UpsertFeeTiersArgs struct {
	FeeTiers []FeeTier `bin:"fee_tiers"`
	Offset   uint8     `bin:"offset"`
}

type UpsertFeeTiersAccounts struct {
	FeeConfig       solana.PublicKey
	Admin           solana.PublicKey
	ConfigProgramId solana.PublicKey
	EventAuthority  solana.PublicKey
	Program         solana.PublicKey
}

func (a UpsertFeeTiersAccounts) ToAccountMetas() []*solana.AccountMeta {
	metas := make([]*solana.AccountMeta, 0, 5)
	metas = append(metas, solana.NewAccountMeta(a.FeeConfig, true, false))
	metas = append(metas, solana.NewAccountMeta(a.Admin, false, true))
	metas = append(metas, solana.NewAccountMeta(a.ConfigProgramId, false, false))
	metas = append(metas, solana.NewAccountMeta(a.EventAuthority, false, false))
	metas = append(metas, solana.NewAccountMeta(a.Program, false, false))
	return metas
}

func BuildUpsertFeeTiers(accounts UpsertFeeTiersAccounts, args UpsertFeeTiersArgs) (solana.Instruction, error) {
	buf := bytes.NewBuffer(make([]byte, 0, 128))
	buf.Write(UpsertFeeTiersDiscriminator)
	if err := bin.NewBorshEncoder(buf).Encode(args); err != nil {
		return nil, fmt.Errorf("encode args: %w", err)
	}
	data := buf.Bytes()
	return solana.NewInstruction(ProgramKey, accounts.ToAccountMetas(), data), nil
}

func DeriveUpsertFeeTiersFeeConfigPDA(accounts UpsertFeeTiersAccounts, args UpsertFeeTiersArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 2)
	seeds = append(seeds, []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103})
	seeds = append(seeds, accounts.ConfigProgramId[:])
	return solana.FindProgramAddress(seeds, ProgramKey)
}

func DeriveUpsertFeeTiersEventAuthorityPDA(accounts UpsertFeeTiersAccounts, args UpsertFeeTiersArgs) (solana.PublicKey, uint8, error) {
	seeds := make([][]byte, 0, 1)
	seeds = append(seeds, []byte{95, 95, 101, 118, 101, 110, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121})
	return solana.FindProgramAddress(seeds, ProgramKey)
}
