// Code generated by internal/gen; DO NOT EDIT.
// Generated at 2026-02-27T14:02:45Z

package pumpfees

import (
	bin "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go"
)

type BondingCurve struct {
	VirtualTokenReserves uint64           `bin:"virtual_token_reserves"`
	VirtualSolReserves   uint64           `bin:"virtual_sol_reserves"`
	RealTokenReserves    uint64           `bin:"real_token_reserves"`
	RealSolReserves      uint64           `bin:"real_sol_reserves"`
	TokenTotalSupply     uint64           `bin:"token_total_supply"`
	Complete             bool             `bin:"complete"`
	Creator              solana.PublicKey `bin:"creator"`
	IsMayhemMode         bool             `bin:"is_mayhem_mode"`
}

type CreateFeeSharingConfigEvent struct {
	Timestamp           int64             `bin:"timestamp"`
	Mint                solana.PublicKey  `bin:"mint"`
	BondingCurve        solana.PublicKey  `bin:"bonding_curve"`
	Pool                *solana.PublicKey `bin:"pool optional"`
	SharingConfig       solana.PublicKey  `bin:"sharing_config"`
	Admin               solana.PublicKey  `bin:"admin"`
	InitialShareholders []Shareholder     `bin:"initial_shareholders"`
	Status              ConfigStatus      `bin:"status"`
}

type FeeConfig struct {
	Bump     uint8            `bin:"bump"`
	Admin    solana.PublicKey `bin:"admin"`
	FlatFees Fees             `bin:"flat_fees"`
	FeeTiers []FeeTier        `bin:"fee_tiers"`
}

type FeeTier struct {
	MarketCapLamportsThreshold bin.Uint128 `bin:"market_cap_lamports_threshold"`
	Fees                       Fees        `bin:"fees"`
}

type Fees struct {
	LpFeeBps       uint64 `bin:"lp_fee_bps"`
	ProtocolFeeBps uint64 `bin:"protocol_fee_bps"`
	CreatorFeeBps  uint64 `bin:"creator_fee_bps"`
}

type Global struct {
	Initialized                 bool                `bin:"initialized"`
	Authority                   solana.PublicKey    `bin:"authority"`
	FeeRecipient                solana.PublicKey    `bin:"fee_recipient"`
	InitialVirtualTokenReserves uint64              `bin:"initial_virtual_token_reserves"`
	InitialVirtualSolReserves   uint64              `bin:"initial_virtual_sol_reserves"`
	InitialRealTokenReserves    uint64              `bin:"initial_real_token_reserves"`
	TokenTotalSupply            uint64              `bin:"token_total_supply"`
	FeeBasisPoints              uint64              `bin:"fee_basis_points"`
	WithdrawAuthority           solana.PublicKey    `bin:"withdraw_authority"`
	EnableMigrate               bool                `bin:"enable_migrate"`
	PoolMigrationFee            uint64              `bin:"pool_migration_fee"`
	CreatorFeeBasisPoints       uint64              `bin:"creator_fee_basis_points"`
	FeeRecipients               [7]solana.PublicKey `bin:"fee_recipients"`
	SetCreatorAuthority         solana.PublicKey    `bin:"set_creator_authority"`
	AdminSetCreatorAuthority    solana.PublicKey    `bin:"admin_set_creator_authority"`
	CreateV2Enabled             bool                `bin:"create_v2_enabled"`
	WhitelistPda                solana.PublicKey    `bin:"whitelist_pda"`
	ReservedFeeRecipient        solana.PublicKey    `bin:"reserved_fee_recipient"`
	MayhemModeEnabled           bool                `bin:"mayhem_mode_enabled"`
	ReservedFeeRecipients       [7]solana.PublicKey `bin:"reserved_fee_recipients"`
}

type InitializeFeeConfigEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
}

type Pool struct {
	PoolBump              uint8            `bin:"pool_bump"`
	Index                 uint16           `bin:"index"`
	Creator               solana.PublicKey `bin:"creator"`
	BaseMint              solana.PublicKey `bin:"base_mint"`
	QuoteMint             solana.PublicKey `bin:"quote_mint"`
	LpMint                solana.PublicKey `bin:"lp_mint"`
	PoolBaseTokenAccount  solana.PublicKey `bin:"pool_base_token_account"`
	PoolQuoteTokenAccount solana.PublicKey `bin:"pool_quote_token_account"`
	LpSupply              uint64           `bin:"lp_supply"`
	CoinCreator           solana.PublicKey `bin:"coin_creator"`
	IsMayhemMode          bool             `bin:"is_mayhem_mode"`
}

type ResetFeeSharingConfigEvent struct {
	Timestamp       int64            `bin:"timestamp"`
	Mint            solana.PublicKey `bin:"mint"`
	SharingConfig   solana.PublicKey `bin:"sharing_config"`
	OldAdmin        solana.PublicKey `bin:"old_admin"`
	OldShareholders []Shareholder    `bin:"old_shareholders"`
	NewAdmin        solana.PublicKey `bin:"new_admin"`
	NewShareholders []Shareholder    `bin:"new_shareholders"`
}

type RevokeFeeSharingAuthorityEvent struct {
	Timestamp     int64            `bin:"timestamp"`
	Mint          solana.PublicKey `bin:"mint"`
	SharingConfig solana.PublicKey `bin:"sharing_config"`
	Admin         solana.PublicKey `bin:"admin"`
}

type Shareholder struct {
	Address  solana.PublicKey `bin:"address"`
	ShareBps uint16           `bin:"share_bps"`
}

type SharingConfig struct {
	Bump         uint8            `bin:"bump"`
	Version      uint8            `bin:"version"`
	Status       ConfigStatus     `bin:"status"`
	Mint         solana.PublicKey `bin:"mint"`
	Admin        solana.PublicKey `bin:"admin"`
	AdminRevoked bool             `bin:"admin_revoked"`
	Shareholders []Shareholder    `bin:"shareholders"`
}

type TransferFeeSharingAuthorityEvent struct {
	Timestamp     int64            `bin:"timestamp"`
	Mint          solana.PublicKey `bin:"mint"`
	SharingConfig solana.PublicKey `bin:"sharing_config"`
	OldAdmin      solana.PublicKey `bin:"old_admin"`
	NewAdmin      solana.PublicKey `bin:"new_admin"`
}

type UpdateAdminEvent struct {
	Timestamp int64            `bin:"timestamp"`
	OldAdmin  solana.PublicKey `bin:"old_admin"`
	NewAdmin  solana.PublicKey `bin:"new_admin"`
}

type UpdateFeeConfigEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
	FeeTiers  []FeeTier        `bin:"fee_tiers"`
	FlatFees  Fees             `bin:"flat_fees"`
}

type UpdateFeeSharesEvent struct {
	Timestamp       int64            `bin:"timestamp"`
	Mint            solana.PublicKey `bin:"mint"`
	SharingConfig   solana.PublicKey `bin:"sharing_config"`
	Admin           solana.PublicKey `bin:"admin"`
	NewShareholders []Shareholder    `bin:"new_shareholders"`
}

type UpsertFeeTiersEvent struct {
	Timestamp int64            `bin:"timestamp"`
	Admin     solana.PublicKey `bin:"admin"`
	FeeConfig solana.PublicKey `bin:"fee_config"`
	FeeTiers  []FeeTier        `bin:"fee_tiers"`
	Offset    uint8            `bin:"offset"`
}
